default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: rails_twitter_development

test:
  <<: *default
  database: rails_twitter_test

production:
  <<: *default
  database: rails_twitter_production
  username: rails_twitter
  password: <%= ENV['RAILS-DOCKER_DATABASE_PASSWORD'] %>
